nome = input('Digite algo: ')
print('O tipo primitivo do que você digitou é: ', type(nome))
print('O que você digitou é alfanumerico: ', nome.isalnum())
print('O que você digitou é numerico: ', nome.isnumeric())
print('O que você digitou é decimal: ', nome.isdecimal())
print('O que você digitou é alfabetico: ', nome.isalpha())
print('O que você digitou é somente espaço: ', nome.isspace())
print('O que você digitou é capitalizado: ', nome.istitle())
print('O que você digitou está em maiúscula: ', nome.isupper())
print('o que você digitou esta em minúscula: ', nome.islower())
print(f'O que você digitou é numérico: {nome.isnumeric()}')
print('O que você digitou é numérico {}'.format(nome.isnumeric()))